"""adiciona coluna itens do pedido

Revision ID: 625c7e44a9c7
Revises: c841899fe79f
Create Date: 2026-02-24 13:10:27.315781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625c7e44a9c7'
down_revision: Union[str, Sequence[str], None] = 'c841899fe79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
